### ISSUE TITLE
Other preinstalled Manifest - Suggestions

### ISSUE THREAD

**Issue by batistein** [cluster-api-provider-hcloud/cluster-api-provider-hcloud#59]
For better collecting ideas here which software we could provide pre-configured:

- Vault
- Prometheus
- Grafana
- Loki
- Octant

**Comment by toonsevrin** [comment]
My objection against this is that it inherently adds opinion into the mix.

I propose the following to improve on this: Don't preinstall anything except a CD tool like [argoCD](https://github.com/argoproj/argo-cd/) which can also still be disabled if people don't need this.

Then you simply aggregate all your manifests with [ArgoCD Application](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/) resources in a separate git project, let's call this the "master repository".

Then finally you create a single `applications.yaml` that points to your master repository (this is called the [App-Of-Apps workflow](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#app-of-apps)).

**Advantages:**
- Everything is deployed through a single apply: `kubectl apply -f applications.yaml`
- The master repository can be reused by other projects
- The master repository can be modified by users
- **Upgrades are managed transparently** (you can define the commit/version you wish to sync with)
- No hardcoded opinionated dependencies within this provider

**Disadvantages:**
- You'd opt into a CD provider. Something that is very opinionated in itself. I personally prefer Argo by a long shot, some people prefer Flux. I propose there's a simple flag to disable this (and thus the easy deployment of all the bootstrap software).

**Bonus points:**
If we can point to our App-Of-Apps in one of the bootstrap CRDs, we've achieved the true declarative "kubernetes as cattle instead of pets" as we don't have to modify any state ourselves.

**Comment by batistein** [comment]
We are now using ClusterResourceSets
